### ISSUE TITLE
latest build is laggy

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [BlueLightJapan/BlueLight#417]
http://timings.pmmp.io/?url=24784979

this lag with just few players online

**Comment by caspervanneck** [comment]
yea but take looke at your plugins

**Comment by caspervanneck** [comment]
they give lag 2

**Comment by caspervanneck** [comment]
and on what are you hosting

**Comment by TDMidkwhatisxd** [comment]
I don't have fancy plugins
essentialsTP v1.1.1, ClearLagg v1.1.0, TimeCommander v2.1, PurePerms v1.4.0-INDEV, WorldProtect v2.3.5, BasicHUD v1.0.6, EconomyAPI v5.7.1, ManyWorlds v2.1.0, SimpleAuth v1.8.1, MagicTelePortal v1.3.2, SAC v3.2.5, MegaBan v1.2.2, RestartMe v1.2.0, iProtector v3.1b, SimpleAuthHelper v2.0.5, AntiSpamPro v1.3.3, EconomySell v2.0.7, EconomyLand v2.0.9, EconomyShop v2.0.7, MyPlot v1.1.4, PureChat v1.4.1

**Comment by Qimie** [comment]
Yeah. The lagg is depends on:~

~ Ur plugin.
~ Core.
~ Server Settings.
~ On what ur hosting.

Wait. Can u give me or  show me ur whole settings file.(Server)

On Jun 6, 2017 12:27 AM, "wesleyvanneck" <notifications@github.com> wrote:

and on what are you hosting

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/BlueLightJapan/BlueLight/issues/417#issuecomment-306234901>,
or mute the thread

**Comment by TDMidkwhatisxd** [comment]
and I noticed a problem, on /status , network upload and download glich , even with no players it keep increasing

**Comment by Qimie** [comment]
Is ur server local or public?

**Comment by HipsterAF** [comment]
Yes theres a memory leak somewhere in the update.

**Comment by ExaSonit** [comment]
clearlagg is useless and check timecommander configuration, maybe you have put a lot of command and magicteleport is useless because you have manyworlds already

**Comment by ExaSonit** [comment]
I'm sorry but this project is abandoned, you can use other spoon like tesseract or other
